// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/config/env';

const fallbackUrl = env.supabaseUrl || 'https://invalid.supabase.local';
const fallbackKey = env.supabaseAnonKey || 'invalid-key';

export const supabase = createClient<Database>(fallbackUrl, fallbackKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
